In [1]:
import pandas as pd

In [2]:
#it is used for read the csv file 
df = pd.read_csv("Used_Bikes.csv")

In [3]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [4]:
#unique function is used for take the unique data from given a column 
df['bike_name'].unique()

array(['TVS Star City Plus Dual Tone 110cc',
       'Royal Enfield Classic 350cc', 'Triumph Daytona 675R',
       'TVS Apache RTR 180cc', 'Yamaha FZ S V 2.0 150cc-Ltd. Edition',
       'Yamaha FZs 150cc', 'Honda CB Hornet 160R  ABS DLX',
       'Hero Splendor Plus Self Alloy 100cc',
       'Royal Enfield Thunderbird X 350cc',
       'Royal Enfield Classic Desert Storm 500cc',
       'Yamaha YZF-R15 2.0 150cc', 'Yamaha FZ25 250cc',
       'Bajaj Pulsar NS200', 'Bajaj Discover 100M', 'Bajaj Discover 125M',
       'Bajaj Pulsar NS200 ABS', 'Bajaj Pulsar RS200 ABS',
       'Suzuki Gixxer SF 150cc', 'Benelli 302R 300CC',
       'Hero Splendor iSmart Plus IBS 110cc',
       'Royal Enfield Classic Chrome 500cc', 'Yamaha FZ V 2.0 150cc',
       'Hero Super Splendor 125cc', 'Honda CBF Stunner 125cc',
       'Bajaj Pulsar 150cc', 'Honda X-Blade 160CC ABS',
       'Bajaj Avenger 220cc', 'KTM RC 390cc', 'Honda CB Unicorn 150cc',
       'KTM Duke 200cc', 'Honda CBR 150R 150cc',
       'Royal Enfield Thunderbird X 500cc', 'KTM RC 200cc ABS',
       'Royal Enfield Thunderbird 350cc',
       'Royal Enfield Bullet Electra 350cc',
       'Bajaj Avenger Street 220 ABS', 'Mahindra Centuro NXT 110cc',
       'Hero Hunk 150cc', 'Suzuki Gixxer SF Fi 150cc SP ABS',
       'Yamaha FZ 150cc', 'Royal Enfield\u200e Bullet 350cc',
       'TVS Apache RTR 160cc', 'Honda CB Shine 125cc',
       'Benelli TNT 600i ABS', 'Honda Dream Yuga 110cc',
       'Yamaha SZ 150cc', 'Suzuki Gixxer 150cc',
       'Bajaj Avenger Cruise 220', 'Kawasaki Z900', 'Bajaj Pulsar 220cc',
       'Hero CD Deluxe 100cc', 'Kawasaki Ninja 650cc',
       'Bajaj Platina 125cc', 'Hero Karizma ZMR 223cc',
       'Bajaj Pulsar 180cc', 'Yamaha FZ25 ABS 250cc',
       'Bajaj CT 100 100cc', 'Royal Enfield Interceptor 650cc',
       'KTM Duke 250cc', 'Royal Enfield Himalayan 410cc',
       'Bajaj Pulsar 135LS', 'Bajaj Pulsar 220F', 'Yamaha FZ16 150cc',
       'Ducati Scrambler 1100 Special', 'Triumph Street Triple 765',
       'Bajaj V15 150cc', 'Suzuki Gixxer Fi 150cc ABS',
       'Hero Splendor plus 100cc', 'KTM Duke 390cc', 'Honda CBR 250R',
       'Bajaj Pulsar RS200', 'Benelli TNT 600i',
       'Suzuki Gixxer 150cc SP Rear Disc', 'Yamaha FZ S V 2.0 150cc',
       'Royal Enfield Classic 500cc', 'Hyosung GT650R',
       'Yamaha YZF-R15 S 150cc', 'TVS Apache RTR 160 4V Disc',
       'Benelli TNT 300', 'Honda CB ShineSP 125cc',
       'Hero Passion Pro 100cc', 'Hero Splendor Plus 100cc',
       'Yamaha YZF R6 600cc', 'Ducati 1299 Superleggera',
       'Royal Enfield Electra 350cc', 'TVS Phoenix Disc 125cc',
       'Harley-Davidson Street 750',
       'Royal Enfield Himalayan 410cc Fi ABS', 'Bajaj Discover 150cc',
       'Bajaj Avenger Street 220', 'Royal Enfield Standard 350cc',
       'Honda CB Shine 125cc Disc', 'Honda CB Unicorn ABS 150cc',
       'Yamaha YZF-R15 V3 150cc', 'Bajaj Pulsar NS 200',
       'Bajaj Dominar 400', 'Honda X-Blade 160cc',
       'Suzuki Hayabusa 1300cc', 'Ducati Monster 821 Dark',
       'Yamaha FZ S V 2.0 150cc Rear Disc',
       'Suzuki Gixxer SF 150cc Special MOTOGP Edition Rear Disc',
       'KTM RC 200cc', 'Bajaj Discover 125ST',
       'Hero Splendor Plus Kick Alloy 100cc', 'Hero Karizma 223cc',
       'Hero Splendor 100cc', 'Ducati 1198 SP 1198cc',
       'Royal Enfield Bullet 500cc', 'Yamaha Fazer 150cc',
       'Yamaha Gladiator 125cc', 'Hero Karizma R 223cc',
       'Harley-Davidson Iron 883', 'TVS Apache RTR 200 4V Fi',
       'TVS Apache RTR 160 4V DISC ABS BS6', 'Bajaj Dominar 400 ABS',
       'Royal Enfield Classic Gunmetal Grey 350cc',
       'Hero HF Deluxe i3s iBS 100cc', 'Suzuki Gixxer SF Fi 150cc ABS',
       'Hero Splendor iSmart 110cc', 'Bajaj Platina 100cc',
       'TVS Apache RTR 200 4V FI', 'Royal Enfield Bullet Twinspark 350cc',
       'TVS Star City 110cc', 'Bajaj Platina  Alloy ES-100cc',
       'Ducati Panigale 959',
       'Royal Enfield Classic 350cc-Redditch Edition', 'TVS Sport 100cc',
       'Bajaj Pulsar AS200',
       'Royal Enfield Classic Desert Storm 500cc Dual Disc',
       'Honda Livo 110cc', 'Suzuki Gixxer SF 150cc SP Rear Disc',
       'Yamaha SZ-RR 150cc', 'Royal Enfield Thunderbird 500cc',
       'Royal Enfield Bullet Electra Twinspark 350cc',
       'Bajaj Discover 150F Disc',
       'Yamaha Saluto 125cc Disc Special Edition',
       'Triumph Street Triple ABS 675cc', 'Honda CBR 250R ABS',
       'Hyosung Aquila GV250', 'Jawa Forty Two 295CC', 'Bajaj V12 125cc',
       'Bajaj V12 125cc Disc', 'Yamaha Fazer 25 250cc',
       'Hero Xpulse 200T', 'Honda CB Hornet 160R CBS',
       'Suzuki Gixxer 150cc SP ABS', 'Hero Passion Xpro 110cc',
       'Yamaha YZF-R3 320cc ABS', 'Royal Enfield Bullet 350 cc',
       'Hero HF Deluxe 100cc', 'Honda CB Twister 110cc',
       'Bajaj Pulsar 125cc Disc CBS', 'Honda CB Shine 125cc Drum BS6',
       'Honda CB Hornet 160R STD', 'Honda Dream Neo 110cc', 'BMW G 310 R',
       'Bajaj Pulsar AS150', 'Kawasaki Ninja 250cc', 'Benelli TNT 899',
       'Indian Chief Classic 1800cc', 'Hero Achiever 150cc',
       'TVS Apache 150cc', 'Kawasaki ER-6n 650cc',
       'Hero HF Deluxe Self 100cc', 'Bajaj Pulsar NS160',
       'Royal Enfield Classic Gunmetal Grey 350cc ABS',
       'Suzuki Intruder 150cc', 'TVS Apache RTR 200 4V ABS Race Edition',
       'Bajaj CT 100 B', 'Hero Passion Pro 110cc Drum',
       'Yamaha YZF-R15 150cc', 'TVS Apache RTR 160 4V DISC ABS',
       'Mahindra Mojo 300cc', 'TVS Apache RTR 200 4V Carburetor',
       'Hero Ignitor Disc 125cc', 'Bajaj Avenger Street 150',
       'Royal Enfield Continental GT 535cc', 'Hero Glamour Disc 125cc',
       'Suzuki Gixxer SF Fi 150cc', 'Hero HF Dawn 100cc',
       'Suzuki Slingshot Plus 125cc', 'Mahindra Centuro Rockstar 110cc',
       'Mahindra Centuro 110cc',
       'Honda CB Hornet 160R Special Edition STD',
       'Harley-Davidson Street Rod XG750A ABS',
       'Hero Splendor Plus IBS i3S 100cc', 'Bajaj Discover 135cc',
       'Bajaj Discover 125cc', 'TVS Apache RTR 160 4V DRUM ABS',
       'Honda CB Unicorn 160 CBS', 'KTM Duke 125cc', 'Bajaj Boxer BM150',
       'Hero Glamour 125cc', 'Bajaj Discover 100cc',
       'Bajaj Avenger Street 180', 'TVS Star City Plus 110cc',
       'Honda CB Trigger 150cc', 'Kawasaki Ninja 650 KRT Edition',
       'Bajaj Platina 100cc ComforTec Alloy', 'Benelli TNT R 1130cc',
       'Honda CB Unicorn Dazzler 150cc', 'Benelli TNT 600 GT',
       'Hyosung GT250R', 'Yamaha YZF-R1 1000cc', 'Hero Xtreme 200R',
       'Ducati Diavel 1200cc', 'Triumph Speed Triple 1050cc',
       'Indian Scout Bobber 1130cc', 'Bajaj V15 150cc POWER UP',
       'Jawa Standard 295CC', 'Yamaha SZR 150cc', 'TVS Star Sport 100cc',
       'Hyosung Aquila 250 250cc', 'Kawasaki Z650', 'Hero CD Dawn 100cc',
       'TVS Apache RTR 200 4V ABS', 'Hero Passion 100cc',
       'Suzuki Intruder SP 150cc', 'Yamaha YZF-R3 320cc',
       'TVS Apache RR310', 'Hero Passion Plus 100cc',
       'Royal Enfield Classic 350cc-Redditch Edition Dual Disc',
       'Hero CBZ 150cc', 'Yamaha FZS FI 150cc',
       'Honda CB Unicorn 160 STD', 'Suzuki GS 150 R 150cc',
       'Royal Enfield Machismo 500cc', 'Hero CBZ Xtreme 150cc',
       'Yamaha SZ RR V 2.0 150cc', 'TVS Apache RTR 180cc ABS',
       'Hero Honda Splendor 100cc', 'Honda CBR 150R Deluxe',
       'Hero Ignitor 125cc', 'Bajaj Pulsar 200cc', 'Kawasaki Ninja 300cc',
       'Kawasaki Ninja 300 ABS', 'Bajaj Pulsar 150cc Rear Disc',
       'Hero Splendor NXG 100cc', 'Hero Achiever Disc 150cc',
       'TVS Apache RTR 200 4V Carburetor Race Edition 2.0',
       'Royal Enfield Thunderbird 350cc ABS',
       'Harley-Davidson Street 750 ABS',
       'Bajaj Pulsar 150cc Rear Disc ABS', 'KTM Duke 250cc ABS',
       'Bajaj Pulsar 200 NS 200cc', 'Mahindra Mojo Tourer Edition 300cc',
       'Hero Passion Pro i3S Alloy 100cc',
       'Royal Enfield Thunderbird X 350cc ABS', 'Hero Xtreme 150cc',
       'Bajaj Boxer CT100', 'Royal Enfield Bullet 350cc',
       'Royal Enfield Standard 500cc', 'Hyosung Aquila Pro GV650',
       'Royal Enfield Classic 500cc Dual Disc', 'Suzuki V-Strom 1000cc',
       'KTM RC 125CC', 'Suzuki Gixxer SF 250cc ABS',
       'Harley-Davidson 1200 Custom', 'Honda Dream Yuga 110cc CBS',
       'Hero Splendor Pro 100cc', 'Suzuki Hayate 110cc',
       'Yamaha Fazer FI V 2.0 150cc', 'TVS Victor 110cc Disc',
       'Royal Enfield Classic Stealth Black 500cc',
       'TVS Apache RTR 200 4V Dual Channel ABS BS6',
       'Honda CB Shine 125cc CBS', 'Honda Livo Disc 110cc',
       'Bajaj Discover 110cc', 'Suzuki Gixxer SF 150cc ABS',
       'Hero CD 100SS', 'Hero Honda Splendor Plus 100cc',
       'Bajaj Discover 100T', 'Hero HF Deluxe self Alloy 100cc',
       'Benelli TNT 25 250cc', 'Yamaha MT-15 150cc',
       'Yamaha FZS FI 150cc Rear Disc',
       'TVS Apache RTR 200 4V Carburetor Pirelli Tyres',
       'Triumph Tiger 800 XRX', 'Ducati XDiavel 1262CC S',
       'TVS Suzuki Shogun 110cc', 'Bajaj Discover 125cc Disc',
       'Triumph Thunderbird Storm 1700cc', 'Suzuki GSX-S750',
       'TVS Flame 125cc', 'Triumph Tiger 800 XCA',
       'Royal Enfield Machismo 350cc', 'TVS Victor 110cc',
       'Honda CBR650R', 'Hero Xpulse 200cc FI',
       'Hero HF Deluxe i3s 100cc',
       'TVS Apache RTR 160cc Matt Red Rear Disc', 'Rajdoot GTX 175cc',
       'Hero Xtreme 200R ABS', 'Honda CB Unicorn 160',
       'Honda CB Hornet 160R Special Edition-CBS',
       'TVS Apache RTR 200 4V Carburetor Pirelli Tyres Race Edition 2.0',
       'TVS Apache RR310 Slipper Clutch', 'Mahindra Mojo UT300',
       'Royal Enfield Bullet Twinspark Kickstart 350cc',
       'Bajaj Pulsar  180cc', 'Honda CD 110 Dream',
       'Royal Enfield Bullet Twinspark 500cc',
       'Hero Xtreme Sports Rear Disc 150cc', 'Bajaj CT 100 ES Alloy',
       'Bajaj  Pulsar 180cc', 'Bajaj Discover 150F', 'Hyosung GT 650N',
       'Triumph Street Twin 900cc', 'Bajaj CT 100 Alloy',
       'TVS Apache RTR 160 4V Drum',
       'Yamaha SZ RR V 2.0 150cc Limited Edition',
       'Yamaha YZF-R1M 1000cc', 'Hero Glamour i3s 125cc',
       'Harley-Davidson Roadster XL 1200CX', 'Triumph Tiger 800 XR',
       'KTM Duke 200cc ABS', 'Honda CBR1000RR Fireblade',
       'Honda SP125 Disc BS6', 'Bajaj Platina 110 H Gear Disc',
       'Hero Splendor Plus 100 cc', 'Honda CBR 250R Repsol',
       'Triumph Bonneville T100 865cc', 'Yamaha RX135 135cc 4-Speed',
       'Benelli 302R', 'Hero Splendor iSmart 100cc',
       'Royal Enfield Classic 350cc Dual Disc', 'Honda CB 1000R',
       'Honda CBR 600RR', 'Ducati Monster 797', 'Ducati Monster 1200',
       'Suzuki GSX-R 1000cc', 'Ducati Monster 796 Corse Stripe',
       'TVS Victor 110cc Disc SBT', 'Honda CB ShineSP 125cc CBS Disc',
       'Kawasaki Z250', 'Royal Enfield Classic Squadron Blue 500cc',
       'Suzuki Gixxer 150cc Dual Tone Rear Disc', 'TVS Apache RTR 200 4V',
       'Honda Livo Disc 110cc CBS', 'TVS Apache RTR 160cc Rear Disc',
       'Yamaha FZ S V 3.0 150cc', 'BMW G 310 GS',
       'Royal Enfield Classic 350cc Signals Edition',
       'Royal Enfield Bullet Electra Twinspark 350cc Double Disc',
       'Honda CB Hornet 160R 160cc STD', 'Suzuki Intruder 150cc FI',
       'Bajaj Platina 110 CBS', 'Hero Xtreme Sports 150cc',
       'Bajaj Avenger Cruise 220 ABS',
       'Honda CB Hornet 160R 160cc STD SP', 'Kawasaki Versys 650cc',
       'Ducati Multistrada 1200 Enduro',
       'Hero Passion Pro i3S Alloy 100cc IBS', 'Hero Xtreme Sports 149cc',
       'TVS Apache RTR 160 4V Carburetor', 'Triumph Thruxton R 1200cc',
       'Honda CD 110 Dream DX', 'BMW S 1000 XR Pro',
       'Honda CB ShineSP 125cc Disc', 'Hero HF Deluxe Eco 100cc',
       'Bajaj XCD 125', 'Honda CB ShineSP 125cc CBS',
       'Bajaj CT110 ES Alloy', 'TVS Apache RTR 160 4V FI',
       'Triumph Bonneville T100 900cc', 'Bajaj Avenger Street 160 ABS',
       'TVS Apache RTR 160cc White Race Edition Rear Disc',
       'Royal Enfield Himalayan 410cc Sleet Edition',
       'Hero Splendor+ 100cc', 'Suzuki Gixxer SF 150cc Rear Disc',
       'TVS Apache RTR 160 4V Carburetor With Rear Disc',
       'Suzuki Heat 125cc', 'Honda CB Hornet 160R  ABS STD',
       'Yamaha Fazer25 250cc', 'Bajaj Pulsar NS160 Rear Disc',
       'Honda CB Hornet 160R', 'Bajaj Discover150 150cc',
       'Bajaj Discover 125T', 'Bajaj Pulsar 150cc Classic',
       'Yamaha Saluto 125cc', 'Hero Passion XPRO 110 cc',
       'Yamaha FZS FI 150cc Special Edition', 'TVS Fiero 150cc',
       'Mahindra Mojo XT300', 'Bajaj Platina Alloy ES 100cc',
       'TVS Jive 110cc', 'Bajaj Boxer AT100', 'Bajaj Discover 150S Disc',
       'TVS Radeon 110cc Drum SBT', 'Honda CD 110 Dream Self',
       'Suzuki Gixxer 150cc ABS', 'Suzuki Hayate EP 110cc',
       'Yamaha SZX 150cc', 'Hero CBZ Star 160cc',
       'Hero Passion PRO  100 cc', 'Hero Passion Pro i3S Disc 100cc',
       'Bajaj Avenger 200cc', 'Hero Honda Ambition 135cc',
       'Bajaj Pulsar 135LS 135cc', 'Bajaj CT 100 KS Alloy',
       'BMW S 1000 RR Pro', 'Kawasaki Versys 1000',
       'Honda CB Unicorn 150 150cc', 'Kawasaki Z800',
       'Hero Glamour PGM Fi 125cc', 'Royal Enfield Continental GT 650cc',
       'LML Freedom DX 110cc', 'Harley-Davidson XG750 750cc',
       'Yezdi Classic 250cc', 'Hero Passion Pro 100cc Drum Alloy',
       'TVS Star 100cc', 'Bajaj XCD 135', 'Bajaj Avenger 150cc',
       'Hero HF Deluxe 100 cc', 'Yamaha Fazer FI 150cc',
       'TVS Apache RTR 200 4V FI Race Edition 2.0',
       'Yamaha FZ V 3.0 150cc', 'Hero Super Splendor 125cc i3s',
       'Yamaha SS 125 125cc',
       'Suzuki Gixxer SF 150cc Special MOTOGP Edition',
       'TVS Victor GX 110cc', 'TVS Apache RTR 200 4V Race Edition 2.0',
       'Hero Passion Pro TR 100cc', 'Honda CBR 650 F',
       'Yamaha FZ S V 3.0 150cc ABS Dark Knight BS VI',
       'Hero HF Deluxe Self Spoke 100cc', 'TVS Sports plus ES 100cc',
       'BMW F750 GS 850cc',
       'Royal Enfield Bullet Electra Twinspark 350CC ABS',
       'Hero Glamour Fi 125cc', 'Royal Enfield Himalayan 410cc Sleet ABS',
       'Bajaj Pulsar NS 200cc', 'Yamaha YBR 110cc', 'Bajaj CT 100 Spoke',
       'Yamaha Crux 110cc', 'Yamaha Saluto RX 110cc',
       'MV Agusta Brutale 1090', 'Royal Enfield Himalayan 410cc Fi',
       'MV Agusta F3 800cc', 'Kawasaki Ninja 400', 'Benelli TRK 502X',
       'TVS Phoenix 125cc', 'Harley-Davidson Fat Bob 107 Ci',
       'TVS Apache RTR 160cc White Race Edition',
       'Ideal Jawa Yezdi CL-II 250 cc', 'Hero Splendor Pro Classic 100cc',
       'Yamaha FZ Fi Version 2.0 150cc', 'Yamaha SZS 150cc',
       'Triumph Daytona 675 ABS',
       'Royal Enfield Classic Chrome 500cc ABS',
       'Harley-Davidson Sportster 883', 'Suzuki Zeus 125cc',
       'Yamaha Saluto 125cc-Special Edition', 'Bajaj Avenger 180cc',
       'Bajaj Pulsar 150cc Neon', 'Kawasaki Z1000',
       'Hero CBZ Xtreme 150 cc', 'Kawasaki Vulcan S 650cc',
       'Yamaha RX-Z 135cc', 'Yamaha Libero G5 110cc',
       'Bajaj Pulsar RS200  ABS-200cc', 'Bajaj Discover150S 150cc',
       'Hero i Smart 125cc', 'Hero Splendor Plus  100 cc',
       'Hero Splendor Plus 100 CC', 'Hero Karizma 223 cc',
       'TVS MAX 4R 110cc', 'Mahindra Pantero 110cc',
       'Hero Ambition 135cc', 'Honda CBR 250R Repsol ABS',
       'Hero Hunk Rear Disc 150cc'], dtype=object)

In [5]:
#it i9s used for count the unique in  brand column
df['brand'].nunique()

23

In [6]:
df['owner'].nunique()

4

In [7]:
# head is used for take the row according to given a nu,mber of row in head function 
df.head(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [8]:
#total brand ki unique brand
df['brand'].value_counts()

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
Yezdi                  1
LML                    1
Name: count, dtype: int64

In [9]:
#dublicati ke liye function name is
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [10]:
#duplicated function is ussed for take  the duplicate data
df.duplicated().sum()

np.int64(25324)

In [11]:
#it is used for drop the duplicated data
df.drop_duplicates(inplace=True)

In [12]:
#it is used for calculate the duplicate data 
df.duplicated().sum()

np.int64(0)

In [13]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [14]:
df.tail()

,bike_name,price,city,kms_driven,owner,age,power,brand
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [15]:
#null ke liye
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [16]:
#null value mko drop karne ke liye
df.dropna(inplace=True)

In [17]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [18]:
#single column drop karna hai
#df.drop('city',axis=1,inplace=True)

In [19]:
df.drop(['bike_name'] , axis=1, inplace=True)

In [20]:
char =df.select_dtypes(include='object')
num =df.select_dtypes(exclude='object')

In [21]:
char

           city        owner            brand
0     Ahmedabad  First Owner              TVS
1         Delhi  First Owner    Royal Enfield
2         Delhi  First Owner          Triumph
3     Bangalore  First Owner              TVS
4     Bangalore  First Owner           Yamaha
...         ...          ...              ...
9362      Delhi  First Owner             Hero
9369  Bangalore  First Owner            Bajaj
9370    Jodhpur  First Owner  Harley-Davidson
9371  Hyderabad  First Owner            Bajaj
9372  Hyderabad  First Owner            Bajaj

[7324 rows x 3 columns]

In [22]:
num

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [23]:
char

           city        owner            brand
0     Ahmedabad  First Owner              TVS
1         Delhi  First Owner    Royal Enfield
2         Delhi  First Owner          Triumph
3     Bangalore  First Owner              TVS
4     Bangalore  First Owner           Yamaha
...         ...          ...              ...
9362      Delhi  First Owner             Hero
9369  Bangalore  First Owner            Bajaj
9370    Jodhpur  First Owner  Harley-Davidson
9371  Hyderabad  First Owner            Bajaj
9372  Hyderabad  First Owner            Bajaj

[7324 rows x 3 columns]

In [24]:
# owner_dict={'First owner':1,'Second  owner':2,'Third owner':3,'Fourth owner or more':4}
# char['owner']=char['owner'].map(owner_dict)

In [25]:
char

           city        owner            brand
0     Ahmedabad  First Owner              TVS
1         Delhi  First Owner    Royal Enfield
2         Delhi  First Owner          Triumph
3     Bangalore  First Owner              TVS
4     Bangalore  First Owner           Yamaha
...         ...          ...              ...
9362      Delhi  First Owner             Hero
9369  Bangalore  First Owner            Bajaj
9370    Jodhpur  First Owner  Harley-Davidson
9371  Hyderabad  First Owner            Bajaj
9372  Hyderabad  First Owner            Bajaj

[7324 rows x 3 columns]

In [26]:
char['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [27]:
brand_dict={'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4}
char['owner']=char['owner'].map(brand_dict)

In [28]:
char

           city  owner            brand
0     Ahmedabad      1              TVS
1         Delhi      1    Royal Enfield
2         Delhi      1          Triumph
3     Bangalore      1              TVS
4     Bangalore      1           Yamaha
...         ...    ...              ...
9362      Delhi      1             Hero
9369  Bangalore      1            Bajaj
9370    Jodhpur      1  Harley-Davidson
9371  Hyderabad      1            Bajaj
9372  Hyderabad      1            Bajaj

[7324 rows x 3 columns]

In [29]:
char['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [30]:
brand_dict={'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
                'Honda':5,          'Hero':6,           'Bajaj':7,          'Suzuki':8,
                'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
                'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
                'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
                'Yezdi':21,              'MV':22,           'Ideal':23}

In [31]:
char['brand']=char['brand'].map(brand_dict)
char

           city  owner  brand
0     Ahmedabad      1      1
1         Delhi      1      2
2         Delhi      1      3
3     Bangalore      1      1
4     Bangalore      1      4
...         ...    ...    ...
9362      Delhi      1      6
9369  Bangalore      1      7
9370    Jodhpur      1     15
9371  Hyderabad      1      7
9372  Hyderabad      1      7

[7324 rows x 3 columns]

In [32]:
char['city'].unique()

array(['Ahmedabad', 'Delhi', 'Bangalore', 'Mumbai', 'Kalyan', 'Faridabad',
       'Mettur', 'Hyderabad', 'Kaithal', 'Gurgaon', 'Pune', 'Noida',
       'Nashik', 'Kochi', 'Allahabad', 'Samastipur', 'Nadiad', 'Lucknow',
       'Jaipur', 'Karnal', 'Gorakhpur', 'Vidisha', 'Hosur', 'Bagalkot',
       'Baripara', 'Agra', 'Dharwad', 'Vadodara', 'Jalandhar', 'Surat',
       'Chennai', 'Navi Mumbai', 'Gandhidham', 'Visakhapatnam',
       'Thrissur', 'Kolkata', 'Ernakulam', 'Barasat', 'Ghaziabad',
       'Bhubaneshwar', 'Amritsar', 'Bhopal', 'Hamirpur(hp)', 'Kottayam',
       'Arrah', 'Patiala', 'Ranga Reddy', 'Mandi', 'Ludhiana', 'Mandya',
       'Siliguri', 'Aurangabad', 'Kanpur', 'Bhilwara', 'Meerut', 'Rewari',
       'Ahmednagar', 'Wardha', 'Chandigarh', 'Ranchi', 'Panvel', 'Thane',
       'Jabalpur', 'Kota', 'Rohtak', 'Rajkot', 'Varanasi', '24 Pargana',
       'Banka', 'Nagpur', 'Banki', 'Pali', 'Chhatarpur', 'Katihar',
       'Mohali', 'Rudrapur', 'Coimbatore', 'Jajpur', 'Mysore', 'Adoni',
       'Bikaner', 'Malout', 'Jammu', 'Rajnandgaon', 'Unnao', 'Godhara',
       'Kolhapur', 'Satara', 'Siwan', 'Dadra & Nagar Haveli', 'Bhiwani',
       'Koppal', 'Nizamabad', 'Madurai', 'Ujjain', 'Palakkad',
       'Tiruvallur', 'Panchkula', 'Nanjangud', 'Jhansi', 'Sonipat',
       'Puttur', 'Hoshiarpur', 'Gohana', 'Gautam Buddha Nagar',
       'Durgapur', 'Palwal', 'Chatrapur', 'Howrah', 'Jind', 'Hubli',
       'Panipat', 'Bharatpur', 'Vellore', 'Ambala', 'Guwahati', 'Gangtok',
       'Rajahmundry', 'Tiruchirappalli', 'Belgaum', 'Balaghat', 'Jatani',
       'Asansol', 'Bilaspur', 'Thanjavur', 'Raigarh(mh)', 'Mandi Dabwali',
       'Basti', 'Bolpur', 'Aligarh', 'Balrampur', 'Ratnagiri', 'Muktsar',
       'Baran', 'Haldwani', 'Thiruvananthapuram', 'Indore', 'Buxar',
       'Chaksu', 'Haridwar', 'Bharuch', 'Muvattupuzha', 'Patna',
       'Simdega', 'Singhbhum', 'Bardhaman', 'Pathankot', 'Kharar',
       'Silchar', 'Jhalawar', 'Roorkee', 'Saharanpur', 'Solapur',
       'Gwalior', 'Alibag', 'Katni', 'Khedbrahma', 'Valsad', 'Satna',
       'Hooghly', 'Gurdaspur', 'Dadri', 'Amravati', 'Durg', 'Mehsana',
       'Lansdowne', 'Cuttack', 'Jaisalmer', 'Hanumangarh', 'Dungarpur',
       'Sri Ganganagar', 'Margao', 'Chinsurah', 'Bhatinda', 'Sibsagar',
       'Khalilabad', 'Dehradun', 'Anand', 'Sambalpur', 'Ankleshwar',
       'Purnia', 'Tiruverkadu', 'Bahadurgarh', 'Udaipur', 'Jodhpur',
       'Sheikhpura', 'Pondicherry', 'Sirsa', 'Godavari', 'Ajmer',
       'Moradabad', 'Raipur', 'Navsari', 'Herbertpur', 'Jamshedpur',
       'Ramanagar', 'Berhampur', 'Vijayawada', 'Murad Nagar',
       'Chandrapur', 'Jamtara', 'Uppidamangalam', 'Nalagarh', 'Una',
       'Chakan', 'Idukki', 'Shivpuri', 'Arkalgud', 'Bidar', 'Rupnagar',
       'Deoghar', 'Kanchipuram', 'Vapi', 'Medak', 'Kasargode', 'Dhanbad',
       'Dakshina Kannada', 'Ganaur', 'Jamalpur', 'Amraoti', 'Mangalore',
       'Deolali', 'Gandhinagar', 'Chitradurga', 'Chinchwad', 'Jhajjar',
       'Jagdalpur', 'Ranoli', 'Raiwala', 'Guntur', 'Badarpur', 'Adalaj',
       'Alipore', 'Bhawani Mandi', 'Mughalsarai', 'Kollam', 'Farukhabad',
       'Thiruvallur', 'Udaipurwati', 'Rasra', 'Latur', 'Krishna',
       'Gangaikondan', 'Warangal', 'Uluberia', 'Poonamallee', 'Nagaon',
       'Hissar', 'Kanyakumari', 'Morbi', 'Bankura', 'Virar', 'Tikamgarh',
       'Sultanpur', 'Tirunelveli', 'Bihar Shariff', 'Goa-panaji',
       'Ganganagar', 'Kolar', 'Bahadurpur', 'Batala', 'Budhlada',
       'Muzaffarnagar', 'Adyar', 'Calicut', 'Raigarh', 'Sonepat',
       'Chikkaballapur', 'Kasba', 'Bulandshahr', 'Burdwan', 'Anjar',
       'Marandahalli', 'Badaun', 'Namakkal', 'Puri', 'Alwar',
       'Surendranagar', 'Khandela', 'Kullu', 'Mohammadabad', 'Sangareddy',
       'Ghazipur', 'Shimla', 'Azamgarh', 'Chenani', 'Kanpur Nagar',
       'Trivandrum', 'Secunderabad', 'Kurukshetra', 'Dhariawad',
       'Bargarh', 'Gadarpur', 'Chikamaglur', 'Karim Nagar', 'Kotdwar',
       'Jalaun', 'Parola', 'Bareilly', 'Salem', 'Indi', 'Muzaffarpur',
       'Nayagarh', 'Jalgaon', 'Ambikapur', 'Udupi', 'Junagadh',
       'Dibrugarh', 'Faridkot', 'Naraingarh', 'Karwar',
       'Sant Kabir Nagar', 'Viramgam', 'Manali', 'Gadwal', 'Honavar',
       'Mathura', 'Khandwa', 'Solan', 'Sitapur', 'Betul', 'Anantapur',
       'Sholapur', 'Pinjore', 'Qadian', 'Sangrur', 'Jorhat', 'Palanpur',
       'Narnaul', 'Palamu', 'Falakata', 'Ferozepur', 'Porbandar',
       'Dwarka', 'Rangpo', 'Cannanore (kannur)', 'Churu', 'Baghpat',
       'Jhumri Tilaiya', 'Naihati', 'Virudhunagar', 'Dharmavaram',
       'Darbhanga', 'Nawanshahr', 'Sangli', 'Suri', 'Yamuna Nagar',
       'Vasai', 'Aluva', 'Sirsi', 'Bijapur', 'Krishnagar', 'Bhiwadi',
       'Bellary', 'Erode', 'Aquem', 'Nellore', 'Udhampur', 'Dhamtari',
       'Vandalur', 'Motihari', 'Dharwar', 'Shimoga', 'Jhunjhunu',
       'Bijnor', 'Yemmiganur', 'Bokaro', 'Kurnool', 'Srinagar', 'Ranip',
       'Davanagere', 'Rajouri', 'Begusarai', 'Goregaon', 'Bally',
       'Kachchh', 'Nagaur', 'Anekal', 'Mansa', 'Nanded', 'Dharamasala',
       'Chhindwara', 'Jamnagar', 'Zirakpur', 'Abohar', 'Barabanki',
       'Nabha', 'Kadapa', 'Perumbavoor', 'Sundargarh', 'Nazira',
       'Pratapgarh', 'Dharmapuri', 'Thangadh', 'Lonavala', 'Vizianagaram',
       'Kathua', 'Deesa', 'Tiruppur', 'Gadchiroli', 'Gangaghat', 'Bhuj',
       'Vastral', 'Phagwara', 'Kheda', 'Swaimadhopur', 'Kharagpur',
       'Jobner', 'Gondia', 'Bundi', 'Hamirpur', 'Dongargaon',
       'Mubarakpur', 'Tumkur', 'Sanand', 'Kartarpur', 'Bhavnagar',
       'Farrukhabad', 'Kadi', 'Seppa', 'Challakere', 'Dhubri', 'Deoria',
       'Akot', 'Alappuzha', 'Bhiwandi', 'Shillong', 'Osmanabad', 'Kendua',
       'Uran', 'Jaunpur', 'Hisar', 'Bodhan', 'Bhubaneswar', 'Raiganj',
       'Bhilai Nagar', 'Baloda', 'Anantnag', 'Berhampore', 'Silvasa',
       'Hospet', 'Palai', 'Sidhi'], dtype=object)

In [33]:
city_dict={'Ahmedabad':1,        'Delhi':2,    'Bangalore':3,       'Mumbai':4,
            'Kalyan':5,    'Faridabad':6,       'Mettur':7,    'Hyderabad':8,
            'Kaithal':9,      'Gurgaon':10,      'Bhubaneswar':11,      'Raiganj':12, 
            'Bhilai Nagar':13,       'Baloda':14, 'Anantnag':15,   'Berhampore':16,      
            'Silvasa':17,       'Hospet':18,        'Palai':19,        'Sidhi':20}
char['city']=char['city'].map(city_dict)

In [34]:
char

      city  owner  brand
0      1.0      1      1
1      2.0      1      2
2      2.0      1      3
3      3.0      1      1
4      3.0      1      4
...    ...    ...    ...
9362   2.0      1      6
9369   3.0      1      7
9370   NaN      1     15
9371   8.0      1      7
9372   8.0      1      7

[7324 rows x 3 columns]

In [35]:
total_df=pd.concat([char,num], axis=1)#es me char or num data frame

In [36]:
total_df

      city  owner  brand     price  kms_driven  age  power
0      1.0      1      1   35000.0     17654.0  3.0  110.0
1      2.0      1      2  119900.0     11000.0  4.0  350.0
2      2.0      1      3  600000.0       110.0  8.0  675.0
3      3.0      1      1   65000.0     16329.0  4.0  180.0
4      3.0      1      4   80000.0     10000.0  3.0  150.0
...    ...    ...    ...       ...         ...  ...    ...
9362   2.0      1      6   25000.0     48587.0  8.0  150.0
9369   3.0      1      7   35000.0     60000.0  9.0  220.0
9370   NaN      1     15  450000.0      3430.0  4.0  750.0
9371   8.0      1      7  139000.0     21300.0  4.0  400.0
9372   8.0      1      7   80000.0      7127.0  5.0  220.0

[7324 rows x 7 columns]

In [37]:
total_df.duplicated().sum()

np.int64(10)

In [38]:
total_df.drop_duplicates(inplace=True)

In [39]:
total_df

      city  owner  brand     price  kms_driven  age  power
0      1.0      1      1   35000.0     17654.0  3.0  110.0
1      2.0      1      2  119900.0     11000.0  4.0  350.0
2      2.0      1      3  600000.0       110.0  8.0  675.0
3      3.0      1      1   65000.0     16329.0  4.0  180.0
4      3.0      1      4   80000.0     10000.0  3.0  150.0
...    ...    ...    ...       ...         ...  ...    ...
9362   2.0      1      6   25000.0     48587.0  8.0  150.0
9369   3.0      1      7   35000.0     60000.0  9.0  220.0
9370   NaN      1     15  450000.0      3430.0  4.0  750.0
9371   8.0      1      7  139000.0     21300.0  4.0  400.0
9372   8.0      1      7   80000.0      7127.0  5.0  220.0

[7314 rows x 7 columns]

In [40]:
#used_bike.csv file is encoded according to this method
total_df.to_csv("Used_bike.csv")

In [41]:
x=total_df.drop('age',axis=1)

In [42]:
x

      city  owner  brand     price  kms_driven  power
0      1.0      1      1   35000.0     17654.0  110.0
1      2.0      1      2  119900.0     11000.0  350.0
2      2.0      1      3  600000.0       110.0  675.0
3      3.0      1      1   65000.0     16329.0  180.0
4      3.0      1      4   80000.0     10000.0  150.0
...    ...    ...    ...       ...         ...    ...
9362   2.0      1      6   25000.0     48587.0  150.0
9369   3.0      1      7   35000.0     60000.0  220.0
9370   NaN      1     15  450000.0      3430.0  750.0
9371   8.0      1      7  139000.0     21300.0  400.0
9372   8.0      1      7   80000.0      7127.0  220.0

[7314 rows x 6 columns]

In [43]:
y=total_df[['age']]

In [44]:
y

      age
0     3.0
1     4.0
2     8.0
3     4.0
4     3.0
...   ...
9362  8.0
9369  9.0
9370  4.0
9371  4.0
9372  5.0

[7314 rows x 1 columns]

In [45]:
import pandas as pd
import numpy as np
import os
df=pd.read_csv('Used_Bikes.csv')

In [46]:
tvs_df=df[df['brand']=='TVS']

In [47]:
tvs_df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
32549,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32568,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32587,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32606,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS

In [48]:
tvs_first_owner_df = tvs_df[tvs_df['owner']=='First Owner']

In [49]:
tvs_first_owner_df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
32549,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32568,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32587,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32606,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS

In [50]:
royal_data=df[(df['brand']=='Royal Enfield')&
              (df['owner']=='First Owner')&
(df['kms_driven']<=50000)&
(df['age']<=2)&
(df['price']<=200000)]

In [51]:
royal_data

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
157,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7422,Royal Enfield Himalayan 410cc Sleet ABS,175000.0,Alipore,1800.0,First Owner,2.0,410.0,Royal Enfield
7559,Royal Enfield Bullet 500cc,170000.0,Delhi,8015.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [52]:
df.query("brand=='Royal Enfield'")

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,First Owner,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,First Owner,5.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
32601,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32614,Royal Enfield Bullet Electra 350cc,105000.0,Delhi,20000.0,First Owner,4.0,350.0,Royal Enfield
32633,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32634,Royal Enfield Thunderbird 350cc,70000.0,Mumbai,13858.0,Second Owner,11.0,350.0,Royal Enfield
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield

In [53]:
bike_data=df